$(function(){var i=introJs();$(window).scroll(function(j){var k=$(document).scrollTop();if(k<=50){$(".nav-fixedbar").removeClass("navbar-fixed-top nav-fixedbar-shadow");
$(".nav-fixedbar .nav-plus").addClass("hidden");$(".nav-fixedbar .navbar-tabs").addClass("nav-plus-invisible");$(".sidebar-offcanvas").removeClass("affix");
}else{if(k>50){$(".nav-fixedbar").addClass("navbar-fixed-top nav-fixedbar-shadow");$(".nav-fixedbar .nav-plus").removeClass("hidden");$(".nav-fixedbar .navbar-tabs").removeClass("nav-plus-invisible");
$(".sidebar-offcanvas").addClass("affix");}}clearTimeout($.data(this,"scrollTimer"));$.data(this,"scrollTimer",setTimeout(function(){h();},50));});$(".nav-fixedbar").dblclick(function(j){b("html");
return false;});$(".navbar-collapse-plus li").click(function(j){d($(".navbar-collapse-plus"));});$("[rel=custom-popover]").click(function(k){var j=$(this).attr("data-target");
$(".popover:not(#"+j+"-popover)").hide().addClass("hidden");$("#"+j+"-popover").fadeIn(300,function(){$("body, #"+j+"-popover button, #"+j+"-popover a").one("click",function(l){$("#"+j+"-popover").fadeOut(300).addClass("hidden");
});}).removeClass("hidden").click(function(l){return false;});return false;});$("#nav-tabs").tab();$("#add").click(function(k){var j=+new Date();a(j,j,false,j);
});$("#changepwd").click(function(){c("changepwd.jsp");});$("#signout").click(function(){location.href="signoutdo";});$("#menu").navgoco({caret:'<span class="caret"></span>',accordion:false,openClass:"open",save:true,cookie:{name:"navgoco",expires:false,path:"/"},slide:{duration:400,easing:"swing"},onClickAfter:function(l,j){l.preventDefault();
if($(this).attr("data-link")){var k=$(this).attr("data-link");inlink=$(this).attr("data-inlink")==undefined?true:$(this).attr("data-inlink"),outlink=$(this).attr("data-outlink")==undefined?false:$(this).attr("data-outlink"),id=$(this).attr("data-index"),title=$(this).text();
if(outlink){window.open(k);}else{if(mobile){c(k);}else{a(id,title,inlink,k);}}if(mobile){$(".row-offcanvas").toggleClass("active");}else{if($(".row-offcanvas").hasClass("active")){$(".row-offcanvas").toggleClass("active");
}if($(".nav-fixedbar").position().top==0){b("#tab-content");}}}}});$("[data-toggle=offcanvas]").click(function(){d($(".navbar-collapse-plus"));$($(this).attr("data-target")).toggleClass("active");
return false;});$(".navbar-tabs .tabs-prev").click(function(j){h("right");});$(".navbar-tabs .tabs-next").click(function(j){h("left");});$(".nav-fixedbar .nav-tabs > li > a > button.close").click(function(k){var j=$(this).parent("a").attr("href");
$(this).parents(".nav-tabs > li").remove();$(j).remove();$("#nav-tabs a:last").tab("show");h();});$(".nav-fixedbar .nav-tabs > li > a").dblclick(function(j){e($(this));
});var g="js/intro.screen.large.json";if(mobile){g="js/intro.screen.small.json";}$.getJSON(g,function(j){i.setOptions({nextLabel:"下一步 &rarr;",prevLabel:"&larr; 上一步",skipLabel:"跳过",doneLabel:"完成",steps:j});
if(!guided){i.start();}});$("#nav-plus-guide").click(function(j){i.start();});f();function f(){var k=$(window).height(),l=$(window).width();var j=$(".row-offcanvas").offset().top;
$(".well.sidebar-nav").css({height:k-j-10});}$(window).resize(function(){f();});function d(j){j.removeClass("in").addClass("collapse");}function c(j){var l=$("<iframe>").attr({src:j,frameborder:0}).css({width:"100%",height:"2000px"}).load(function(){});
var k=$("<div>").append(l);$("#tab-content").empty().append(k);}function a(p,m,j,o){if($("#nav-tabs a[href=#"+p+"]").length!=0){$("#nav-tabs a[href=#"+p+"]").tab("show");
return false;}var l=$("<button>").text("×").addClass("close closeTab").click(function(r){var q=$(this).parent("a").attr("href");$(this).parents(".nav-tabs > li").remove();
$(q).remove();$("#nav-tabs a:last").tab("show");h();});var k=$("<a>").text(m).attr({"data-toggle":"tab",href:"#"+p}).prepend(l).dblclick(function(q){e($(this));
});$("<li>").append(k).appendTo($("#nav-tabs"));var n="";if(j){n=$("<iframe>").attr({src:o,frameborder:0}).css({width:"100%"}).load(function(){this.style.height="2000px";
});}else{n=o;}$("<div>").attr({id:p}).addClass("tab-pane").append(n).appendTo($("#tab-content"));$("#nav-tabs a:last").tab("show");h();}function e(k){var j=k.attr("href");
k.parents("li").remove();$(j).remove();$("#nav-tabs a:last").tab("show");h();}function h(){h(null);}function h(n){var p=$(".nav-tabs-wrap").width();var m=0,o=150,l=200;
$.each($("#nav-tabs > li"),function(q,r){m+=$(r).width();});if(m>p){if(n==null){$(".nav-tabs").animate({"margin-left":p-m},l);$(".navbar-tabs .tabs-prev").addClass("active").removeClass("hidden");
$(".navbar-tabs .tabs-next").removeClass("hidden");}else{var j=m-p,k=$(".nav-tabs").css("margin-left").replace("px","").replace("-","");if(n=="right"){if(k-o<0){o=0;
$(".navbar-tabs .tabs-prev").removeClass("active");}else{o=o-k;$(".navbar-tabs .tabs-prev, .navbar-tabs .tabs-next").addClass("active");}$(".nav-tabs").animate({"margin-left":o},l);
}else{if(j-o-k<=0){o=0-j;$(".navbar-tabs .tabs-next").removeClass("active");}else{o=0-o-k;$(".navbar-tabs .tabs-prev, .navbar-tabs .tabs-next").addClass("active");
}$(".nav-tabs").animate({"margin-left":o},l);}}}else{if($(".nav-tabs").css("margin-left")<"0px"){$(".nav-tabs").animate({"margin-left":0},l).removeAttr("margin-left");
$(".navbar-tabs .tabs-prev, .navbar-tabs .tabs-next").addClass("hidden").removeClass("active");}}}function b(l){var k=800;var j=jQuery(l).offset().top;
jQuery("html:not(:animated),body:not(:animated)").animate({scrollTop:j},k,function(){window.location.hash=l;});return false;}});